baseurl = "https://automato-build.github.io/website/"
languageCode = "en-us"
title = "My New Hugo Site"
theme ="automato"

[params]

	# You can use Markdown syntax for urls [text](//url.to/source) for
	# most longer texts.

	# All blog posts are defined in their own files.

  # Navigation
	[params.navigation]
		brand = "a u t o m a t o . f a r m"

	[[params.navigation.links]]
    name     = "works"
    link = "/portfolio"

  [[params.navigation.links]]
    name     = "about"
    link = "/about"

  [[params.navigation.links]]
    name     = "experiments"
    link = "/experiments"

  #section hero
  [params.hero]
  claim="Research, design & prototype from 7 hours in the future"
  backgroundImages=["plugs.jpg","hi.jpg","dog.gif"]

  #section portfolio
  [params.portfolio]
  title="We research and develop future products and interfaces sometimes real sometimes fictional."
  more="See all projects"
  morelink="/research"

  #section blog
  [params.blog]
  title="We collaborate with studios, companies and institutions to ideate & prototype with emerging technologies"
  more="More about automato.farm"
  morelink="/about"

  #section research
  [params.research]
  title="We teach, talk and research the complex relationships between people and machines"
  more="get in touch"
  morelink=""

  #section footer
  [params.footer]
  claim="We think about the future so you don’t have to."
  subtitle="We are based in Shanghai, Contact us."
  link=""

  [[params.footer.social]]
  name="email"
  link="mailto:hi.automato.farm"
  icon="fa-envelope-o"

  [[params.footer.social]]
  name="facebook"
  link="https://www.facebook.com/automatofarm/"
  icon="fa-facebook"

  [[params.footer.social]]
  name="twitter"
  link="https://twitter.com/automato_farm"
  icon="fa-twitter"

  [[params.footer.social]]
  name="vimeo"
  link="https://vimeo.com/automato"
  icon="fa-vimeo"

  [[params.footer.social]]
  name="instagram"
  link="https://www.instagram.com/automato.farm/"
  icon="fa-instagram"
