baseurl = "https://automato-build.github.io/website/"
languageCode = "en-us"
title = "My New Hugo Site"
theme ="automato"

[params]

	# You can use Markdown syntax for urls [text](//url.to/source) for
	# most longer texts.

	# All blog posts are defined in their own files.

  # Navigation
	[params.navigation]
		brand = "a u t o m a t o"

	[[params.navigation.links]]
    name     = "works"
    link = "/portfolio"
  [[params.navigation.links]]
    name     = "research"
    link = "/research"
  [[params.navigation.links]]
    name     = "about"
    link = "/about"
  [[params.navigation.links]]
    name     = "market"
    link = "/market"
  [[params.navigation.links]]
    name     = "blog"
    link = "/blog"

  #section hero
  [params.hero]
  claim="Research, design & prototype from 7 hours in the future"
  backgroundGif="politicsofpower.gif"

    [params.hero.auto]
    title="a u t o "
    replacement_words= ["factory","design","things", "real"]
    claim="we prototype for you"
    openingTime="9am-9pm"


    [params.hero.mato]
    title="m a t o "
    replacement_words= ["farm","art","research", "fiction"]
    claim="research in the intersection of technology and society"
    openingTime="9pm-9am"


  #section portfolio
  [params.portfolio]
  title="We research and develop future products and interfaces sometimes real sometimes fictional."
  more="See all projects"
  morelink="/research"

  #section blog
  [params.blog]
  title="We collaborate with studios, companies and institutions to ideate & prototype with emerging technologies"
  more="More about automato.farm"
  morelink="/about"

  #section research
  [params.research]
  title="We teach, talk and research the complex relationships between people and machines"
  more="get in touch"
  morelink=""

  #section footer
  [params.footer]
  claim="We think about the future so you don’t have to."
  subtitle="We are based in Shanghai, Contact us."
  link=""
